# Generated by Django 5.1.7 on 2025-03-24 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('game_type', models.CharField(choices=[('tic_tac_toe', 'Tic-Tac-Toe'), ('flappy_bird', 'Flappy Bird'), ('hanoi', 'Tower of Hanoi'), ('other', 'Other')], max_length=50)),
                ('completion_condition', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('completed_levels', models.JSONField(default=list)),
                ('total_time_spent', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
