# Generated by Django 5.1.7 on 2025-03-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='completed_levels',
            field=models.IntegerField(default=0),
        ),
    ]
